# Site settings
title: "Martial Testing"
tagline: Because Testing is NaN
email: iesmite@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martialtesting.com" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
github:  [metadata]
# from github documentation
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
 noscript: false
# //from github documentation

# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: martialtesting
    twitter: MartialTesting
    facebook: MartialTesting

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: martialtesting

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: "UA-40132135-1"
  #google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 3
gems:
  - jekyll-coffeescript
  - jekyll-paginate
paginate_path: "page:num"

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

kramdown:
 input: GFM
 hard_wrap: false
